### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by jcabello7** [jellyfin/jellyfin-samsungtv#6]
It's working?
There are any guide about how to install?
There are binaries compiled?
Thanks in advance and great work!

**Comment by vaxevanis** [comment]
@jcabello7 this app is working just fine in any Samsung Legacy TV model, running Orsay (pre-2015), aka non Tizen.  You can see a list of Samsung TV models [here](https://developer.samsung.com/smarttv/develop/specifications/tv-model-groups.html)

As for the installation guide, you can use a usb stick(should be connected to the tv at all times) or  download the zip and host it on your own web server

**Jellyfin Legacy Samsung app installation instructions for Windows server:**
1. Download the zip file jellyfin-samsungtv-master.zip.
2. Extract content and zip all content of the jellyfin-samsungtv-master folder to a new zip file called ex. jellyfin.zip.Copy the zip file to a subfolder ex: Widgets under the root of the default download folder on your web server
I'm using IIS and the zip file is in:

C:\inetpub\wwwroot\Widgets\jellyfin.zip    (example filename) 

3. Create a file called widgetlist.xml in the root folder

C:\inetpub\wwwroot\widgetlist.xml


Place this information in the xml file changing the IP to your web server's IP and the filename if needed.

```<?xml version="1.0" encoding="UTF-8"?>
<rsp stat="ok">
<list>
<widget id="Jellyfin">
<title>jellyfin</title>
<compression type="zip" size="919000"/>
<description/>
<download>http://192.168.x.x/Widgets/jellyfin.zip</download>
</widget>
</list>
</rsp>
```


4. Install the app using your own web server's IP and the appropriate instructions for your model year TV. Look [here](https://emby.media/community/index.php?/topic/9869-samsung-smart-tv-app-install-instructions/?p=277346)

**Comment by JulioNahum** [comment]
To install via USB, all you need to do is download the zip, move it to the usb, connect it to the TV and it will only install? or do we have to do some more steps?

**Comment by kudumi** [comment]
I did try both USB and web server, it doesn't get installed, what am I doing wrong?

**Comment by manjotsc** [comment]
@kudumi make sure size value, you need to change size value <compression type="zip" size="**919000**"/> to the exact size of your **jellyfin.zip**

**Comment by ShaheedHaque** [comment]
@vaxevanis Are the instruction on unpacking and repacking the download from Github perhaps not quite right? I ask because:

1. the size of the resulting file is 983633 bytes, and setting that in the widgetlist.xml results in a failed install
    -  the only clue from the TV is a hint to navigate to some non-existent Samsung TVAppSecurity URL, and then an empty dialog
2. the size of the Emby_2.2.9_Europe_20210518.zip is 962226, and the size in widgetlist.xml is only 919000, but it results in a clean download
    - it then fails to run for unknown reasons against the Jellyfin server.

Is there any way to get more useful diagnostics from the TV?

**Comment by ShaheedHaque** [comment]
OK, the key to getting the download to work is to ensure that when the zip file is repacked:

- the content must be in the top level of the zip (i.e. not under the directory jellyfin-samsungtv-master).
- the filename has to have the form Jellyfin_&lt;version&gt;\_&lt;region&gt;\_&lt;date&gt;.zip (e.g. Jellyfin_2.2.5b_Europe_20210518.zip).

At this point, I can install and launch the app!

**Comment by sirodepom** [comment]
I am blocked in the installation process.
- by USB it works, but it's reset each time the TV is powered again (need to indicate the server IP each time...), so not useful.
- by IP, I come to the point when the TV says "The following new service will be installed automatically", but the file is never downloaded. 
The issue looks very similar to the previous mentions, but the given solutions don't work for me. I have no idea what to try.

**Comment by ShaheedHaque** [comment]
Did you follow the linked instructions in terms of setting up your Web server, and in terms of editing the script I provided tocontain the address of your webserver? If you did, then try using a browser to fetch your file? Use that to debug your setup.

**Comment by sirodepom** [comment]
Hey now it works!
I'm so happy :-)

@ShaheedHaque
I looked to the script but I was not able to use it, I'm not advanced enough for that. I strictly follow your recommendations of naming (but I already did yesterday...). I'm on windows 10, I noticed that the jellyfin server was not able to transfer the file, but I had no clue why. So I maintained a server with XAMPP (Apache) until the TV took the file.

Regarding the solution, I don't really see what I did different of yesterday, but I'll try to mention what I can in case it can help someone:
- I used this file of the 2.2.9 using the link you post some comments before, so pehaps the issue was from the file itself. It's not the one which come by default on this GitHub.
- I zipped it after deleting readme.md and package.sh
- I indicated the exact size in the xml.
- and I tried 3 / 4 times on the TV...
 
Good surprise to see that you prepared the 2.2.9 with jellyfin logos 👍 
Thanks for all the efforts!

**Comment by sermayoral** [comment]
Hi friends.

I'm also interested on install this. Where can i find the 2.2.9 app? I don't find it anywhere.

Thanks in advance :-)

**Comment by SEPPDROID** [comment]
For anyone still commenting and trying to install the Jellyfin app on a Samsung Smart TV with the Orsay arch (pre 2015)

Login with developer account and set the "IP SETTING" to 128.199.50.45 then click "Start User App Sync" 

After a few seconds the Jellyfin widget will install, it's the one from this repository. Please note that this app is very outdated and unsupported but as off today still works decently. I also still have friends with (old) samsung tv's watching movies like this ;)

For usb install just download the zip file and place it in a subdirectory to sideload offline
http://128.199.50.45/Widgets/Jellyfin_2.2.5b_Europe_20210518.zip

_Please also note that jellyfin behind reverse proxy + certificate will likely not work on most older tv's without being creative like creating another reverse proxy (ex. insecure.jellyfin.mydomain.tld:80)_

**Comment by Salter314** [comment]
Doesn't work with server version > 10.9.x. (latest is 10.10.3)
Version comparison in serverversion.js is unluckily implemented

**Comment by ronin2011** [comment]
I did all the IIS steps, and the app installed successfully, once i started it and entered the server ip it said "The samsung app requires an updated version of the server" even though i am on the most up to date jellyfin server
